# Form implementation generated from reading ui file 'c:\Users\hp\Documents\CS_Undergrad\Semester_3\DATABASE\DB project\DairyPro-main\Code-Connection\Screens\29 Customer Product Button.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(753, 622)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.booksTableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.booksTableWidget.setGeometry(QtCore.QRect(30, 290, 531, 191))
        self.booksTableWidget.setStyleSheet("QTableWidget {\n"
"    background-color: rgb(169, 192, 255);\n"
"   alternate-background-color: #e0e0e0;\n"
"   selection-background-color: #4CAF50;\n"
"    border:  rgb(0, 0, 127);; /* Border color around the table */\n"
"    margin: 5px; /* Set the margin size */\n"
"    font: 8pt \"Comic Sans MS\";\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    font: 8pt \"Comic Sans MS\";\n"
"    color: rgb(0, 0, 127);\n"
"    \n"
"}\n"
"\n"
"\n"
"QHeaderView::section {\n"
"    background-color:  rgb(169, 192, 255); /* Header background color */\n"
"    color: rgb(0, 0, 127); /* Header text color */\n"
"    padding: 4px; /* Header padding */\n"
"    font: 8pt \"Comic Sans MS\";\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: rgb(0, 0, 127) /* Background color for selected items */\n"
"    color: white; /* Text color for selected items */\n"
"}\n"
"")
        self.booksTableWidget.setObjectName("booksTableWidget")
        self.booksTableWidget.setColumnCount(6)
        self.booksTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setHorizontalHeaderItem(5, item)
        self.searched = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.searched.setGeometry(QtCore.QRect(30, 80, 521, 191))
        self.searched.setStyleSheet("font: 10pt \"Comic Sans MS\";\n"
"border-color: rgb(0, 0, 127);\n"
"border-width: 10px;\n"
"color: rgb(0, 0, 127);")
        self.searched.setObjectName("searched")
        self.type = QtWidgets.QGroupBox(parent=self.searched)
        self.type.setGeometry(QtCore.QRect(330, 30, 171, 171))
        self.type.setStyleSheet("font: 10pt \"Comic Sans MS\";\n"
"border-color: rgb(0, 0, 127);\n"
"border-width: 10px;\n"
"color: rgb(0, 0, 127);")
        self.type.setObjectName("type")
        self.layoutWidget = QtWidgets.QWidget(parent=self.type)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 120, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rdb1 = QtWidgets.QRadioButton(parent=self.layoutWidget)
        self.rdb1.setObjectName("rdb1")
        self.verticalLayout_3.addWidget(self.rdb1)
        self.rdb2 = QtWidgets.QRadioButton(parent=self.layoutWidget)
        self.rdb2.setObjectName("rdb2")
        self.verticalLayout_3.addWidget(self.rdb2)
        self.rdb3 = QtWidgets.QRadioButton(parent=self.layoutWidget)
        self.rdb3.setObjectName("rdb3")
        self.verticalLayout_3.addWidget(self.rdb3)
        self.rdb3_2 = QtWidgets.QRadioButton(parent=self.layoutWidget)
        self.rdb3_2.setObjectName("rdb3_2")
        self.verticalLayout_3.addWidget(self.rdb3_2)
        self.issueCheck = QtWidgets.QCheckBox(parent=self.searched)
        self.issueCheck.setGeometry(QtCore.QRect(30, 110, 71, 20))
        self.issueCheck.setStyleSheet("font: 8pt \"Comic Sans MS\";\n"
"color:rgb(0, 0, 127)\n"
"")
        self.issueCheck.setObjectName("issueCheck")
        self.searchButton = QtWidgets.QPushButton(parent=self.searched)
        self.searchButton.setGeometry(QtCore.QRect(170, 110, 121, 31))
        self.searchButton.setStyleSheet("background-color: rgb(174, 209, 255);\n"
"font: 10pt \"Comic Sans MS\";\n"
"color: #00007f;\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;\n"
"")
        self.searchButton.setObjectName("searchButton")
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.searched)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 30, 87, 61))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label.setStyleSheet("font: 8pt \"Comic Sans MS\";\n"
"color:rgb(0, 0, 127)\n"
"")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_2.setStyleSheet("font: 8pt \"Comic Sans MS\";\n"
"color:rgb(0, 0, 127)\n"
"")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.layoutWidget2 = QtWidgets.QWidget(parent=self.searched)
        self.layoutWidget2.setGeometry(QtCore.QRect(130, 30, 161, 61))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.categoryCombo = QtWidgets.QComboBox(parent=self.layoutWidget2)
        self.categoryCombo.setStyleSheet("background-color: rgb(169, 192, 255);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;")
        self.categoryCombo.setObjectName("categoryCombo")
        self.verticalLayout_2.addWidget(self.categoryCombo)
        self.price = QtWidgets.QLineEdit(parent=self.layoutWidget2)
        self.price.setStyleSheet("background-color: rgb(169, 192, 255);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;")
        self.price.setText("")
        self.price.setObjectName("price")
        self.verticalLayout_2.addWidget(self.price)
        self.closeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(430, 500, 121, 31))
        self.closeButton.setStyleSheet("background-color: rgb(174, 209, 255);\n"
"font: 10pt \"Comic Sans MS\";\n"
"color: #00007f;\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;\n"
"")
        self.closeButton.setObjectName("closeButton")
        self.viewButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.viewButton.setGeometry(QtCore.QRect(300, 500, 121, 31))
        self.viewButton.setStyleSheet("background-color: rgb(174, 209, 255);\n"
"font: 10pt \"Comic Sans MS\";\n"
"color: #00007f;\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;\n"
"")
        self.viewButton.setObjectName("viewButton")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(-20, -10, 811, 671))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("\n"
"\n"
"background-color: rgb(207, 232, 255);\n"
"")
        self.label_4.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(180, 20, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("")
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_4.raise_()
        self.booksTableWidget.raise_()
        self.searched.raise_()
        self.closeButton.raise_()
        self.viewButton.raise_()
        self.label_12.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 753, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.booksTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.booksTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.booksTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Type"))
        item = self.booksTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Price"))
        item = self.booksTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Ingredients"))
        item = self.booksTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "In Stock"))
        self.searched.setTitle(_translate("MainWindow", "Search"))
        self.type.setTitle(_translate("MainWindow", "Type"))
        self.rdb1.setText(_translate("MainWindow", "Infant Formula"))
        self.rdb2.setText(_translate("MainWindow", "Tea Whitener"))
        self.rdb3.setText(_translate("MainWindow", "Coffee Creamer"))
        self.rdb3_2.setText(_translate("MainWindow", "Powdered Milk"))
        self.issueCheck.setText(_translate("MainWindow", "In Stock"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.label.setText(_translate("MainWindow", "Product Name:"))
        self.label_2.setText(_translate("MainWindow", "Price:"))
        self.closeButton.setText(_translate("MainWindow", "Close"))
        self.viewButton.setText(_translate("MainWindow", "View"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00007f;\">Search Product</span></p></body></html>"))
