# Form implementation generated from reading ui file 'c:\Users\hp\Documents\CS_Undergrad\Semester_3\DATABASE\DB project\DairyPro-main\Code-Connection\Screens\40 Supplier Order form.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(547, 590)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.searched = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.searched.setGeometry(QtCore.QRect(10, 20, 511, 221))
        self.searched.setStyleSheet("font: 10pt \"Comic Sans MS\";\n"
"border-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 127);\n"
"border-width: 10px;\n"
"color: rgb(0, 0, 127);")
        self.searched.setObjectName("searched")
        self.supp_order_search = QtWidgets.QPushButton(parent=self.searched)
        self.supp_order_search.setGeometry(QtCore.QRect(260, 120, 111, 31))
        self.supp_order_search.setStyleSheet("background-color: rgb(174, 209, 255);\n"
"font: 10pt \"Comic Sans MS\";\n"
"color: #00007f;\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;\n"
"")
        self.supp_order_search.setObjectName("supp_order_search")
        self.label_6 = QtWidgets.QLabel(parent=self.searched)
        self.label_6.setGeometry(QtCore.QRect(270, 10, 90, 62))
        self.label_6.setStyleSheet("font: 10pt \"Comic Sans MS\";\n"
"font-color: rgb(0, 0, 127);")
        self.label_6.setObjectName("label_6")
        self.mat_name = QtWidgets.QLineEdit(parent=self.searched)
        self.mat_name.setGeometry(QtCore.QRect(270, 60, 111, 20))
        self.mat_name.setStyleSheet("background-color: rgb(169, 192, 255);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;")
        self.mat_name.setObjectName("mat_name")
        self.booksTableWidget = QtWidgets.QTableWidget(parent=self.searched)
        self.booksTableWidget.setGeometry(QtCore.QRect(20, 20, 231, 191))
        self.booksTableWidget.setStyleSheet("QTableWidget {\n"
"    background-color: rgb(169, 192, 255);\n"
"   alternate-background-color: #e0e0e0;\n"
"   selection-background-color: #4CAF50;\n"
"    border:  rgb(0, 0, 127);; /* Border color around the table */\n"
"    margin: 5px; /* Set the margin size */\n"
"    font: 8pt \"Comic Sans MS\";\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    font: 8pt \"Comic Sans MS\";\n"
"    color: rgb(0, 0, 127);\n"
"    \n"
"}\n"
"\n"
"\n"
"QHeaderView::section {\n"
"    background-color:  rgb(169, 192, 255); /* Header background color */\n"
"    color: rgb(0, 0, 127); /* Header text color */\n"
"    padding: 4px; /* Header padding */\n"
"    font: 8pt \"Comic Sans MS\";\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: rgb(0, 0, 127) /* Background color for selected items */\n"
"    color: white; /* Text color for selected items */\n"
"}\n"
"")
        self.booksTableWidget.setObjectName("booksTableWidget")
        self.booksTableWidget.setColumnCount(3)
        self.booksTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setHorizontalHeaderItem(2, item)
        self.viewButton = QtWidgets.QPushButton(parent=self.searched)
        self.viewButton.setGeometry(QtCore.QRect(260, 170, 111, 31))
        self.viewButton.setStyleSheet("background-color: rgb(174, 209, 255);\n"
"font: 10pt \"Comic Sans MS\";\n"
"color: #00007f;\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;\n"
"")
        self.viewButton.setObjectName("viewButton")
        self.generateOrder = QtWidgets.QPushButton(parent=self.searched)
        self.generateOrder.setGeometry(QtCore.QRect(380, 120, 111, 31))
        self.generateOrder.setStyleSheet("background-color: rgb(174, 209, 255);\n"
"font: 10pt \"Comic Sans MS\";\n"
"color: #00007f;\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;\n"
"")
        self.generateOrder.setObjectName("generateOrder")
        self.closeButton = QtWidgets.QPushButton(parent=self.searched)
        self.closeButton.setGeometry(QtCore.QRect(380, 170, 111, 31))
        self.closeButton.setStyleSheet("background-color: rgb(174, 209, 255);\n"
"font: 10pt \"Comic Sans MS\";\n"
"color: #00007f;\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;\n"
"")
        self.closeButton.setObjectName("closeButton")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, -70, 781, 651))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("\n"
"\n"
"background-color: rgb(207, 232, 255);\n"
"")
        self.label_4.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.searched.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 547, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.searched.setTitle(_translate("MainWindow", "Search"))
        self.supp_order_search.setText(_translate("MainWindow", "Search"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00007f;\">Material Name:</span></p></body></html>"))
        self.mat_name.setText(_translate("MainWindow", "011245"))
        item = self.booksTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Material Name"))
        item = self.booksTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Cost"))
        item = self.booksTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Inventory Level"))
        self.viewButton.setText(_translate("MainWindow", "View"))
        self.generateOrder.setText(_translate("MainWindow", "Generate Order"))
        self.closeButton.setText(_translate("MainWindow", "Close"))
