# Form implementation generated from reading ui file 'c:\Users\hp\Documents\CS_Undergrad\Semester_3\DATABASE\bd_final_project\DairyPro\DB_ConnectionsFiles\DB_project\41 Supplier View Order Form.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(490, 419)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.closeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(310, 320, 121, 31))
        self.closeButton.setStyleSheet("background-color: rgb(174, 209, 255);\n"
"font: 10pt \"Comic Sans MS\";\n"
"color: #00007f;\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;\n"
"")
        self.closeButton.setObjectName("closeButton")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(-10, -20, 691, 461))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("\n"
"\n"
"background-color: rgb(207, 232, 255);\n"
"")
        self.label_4.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 140, 90, 57))
        self.label_5.setStyleSheet("font: 8pt \"Comic Sans MS\";")
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 90, 90, 57))
        self.label_2.setStyleSheet("font: 8pt \"Comic Sans MS\";")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 40, 90, 77))
        self.label.setStyleSheet("font: 8pt \"Comic Sans MS\";")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 170, 90, 81))
        self.label_3.setStyleSheet("font: 8pt \"Comic Sans MS\";")
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 220, 90, 81))
        self.label_7.setStyleSheet("font: 8pt \"Comic Sans MS\";")
        self.label_7.setObjectName("label_7")
        self.inven_levl = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.inven_levl.setGeometry(QtCore.QRect(158, 200, 251, 20))
        self.inven_levl.setStyleSheet("background-color: rgb(169, 192, 255);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;")
        self.inven_levl.setObjectName("inven_levl")
        self.cost_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.cost_line.setGeometry(QtCore.QRect(158, 250, 251, 20))
        self.cost_line.setStyleSheet("background-color: rgb(169, 192, 255);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;")
        self.cost_line.setObjectName("cost_line")
        self.mat_id = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.mat_id.setGeometry(QtCore.QRect(158, 70, 251, 20))
        self.mat_id.setStyleSheet("background-color: rgb(169, 192, 255);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;")
        self.mat_id.setObjectName("mat_id")
        self.mat_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.mat_name.setGeometry(QtCore.QRect(158, 110, 251, 20))
        self.mat_name.setStyleSheet("background-color: rgb(169, 192, 255);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;")
        self.mat_name.setObjectName("mat_name")
        self.sup_id = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.sup_id.setGeometry(QtCore.QRect(158, 160, 251, 20))
        self.sup_id.setStyleSheet("background-color: rgb(169, 192, 255);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;")
        self.sup_id.setObjectName("sup_id")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(160, 10, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("")
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_4.raise_()
        self.closeButton.raise_()
        self.label_5.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.label_7.raise_()
        self.inven_levl.raise_()
        self.cost_line.raise_()
        self.mat_id.raise_()
        self.mat_name.raise_()
        self.sup_id.raise_()
        self.label_12.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 490, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.closeButton.setText(_translate("MainWindow", "Close"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00007f;\">Supplier ID:</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00007f;\">Material Name:</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00007f;\">Material ID:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00007f;\">Inventory Level:</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00007f;\">Cost:</span></p></body></html>"))
        self.inven_levl.setText(_translate("MainWindow", "500"))
        self.cost_line.setText(_translate("MainWindow", "112244"))
        self.mat_id.setText(_translate("MainWindow", "56"))
        self.mat_name.setText(_translate("MainWindow", "1001"))
        self.sup_id.setText(_translate("MainWindow", "112244"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00007f;\">Order Details</span></p></body></html>"))
